+incdir+../src
../deps/async_fifo/src/vlog/async_fifo.v
../deps/async_fifo/src/vlog/fifo_2mem.v
../deps/async_fifo/src/vlog/fifomem_dp.v
../deps/async_fifo/src/vlog/rptr_empty.v
../deps/async_fifo/src/vlog/sync_ptr.v
../deps/async_fifo/src/vlog/sync_r2w.v
../deps/async_fifo/src/vlog/sync_w2r.v
../deps/async_fifo/src/vlog/wptr_full.v
../src/bster.sv
../src/bst_engine.sv
../src/insert_engine.sv
../src/search_engine.sv
../src/delete_engine.sv
../src/csr.sv
../src/interface_handler.sv
../src/tree_space_manager.sv
../src/memory_driver.sv
../src/axi_ram.sv
+define+VERBOSE
+define+TIMEOUT=1000
